language: rust

cache:
  directories:
    - /home/travis/.cargo

before_cache:
  - rm -rf /home/travis/.cargo/registry

install: |
  # this project's rustfmt style requires nightly features
  if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
    rustup component add rustfmt
  fi

matrix:
  include:
  - rust: 1.40.0
  - rust: stable
  - rust: beta
  - rust: nightly
    env: ALLOW_FAILURES=true
  - os: osx
  - env: TARGET=x86_64-unknown-linux-musl
  - env: TARGET=x86_64-unknown-linux-gnu
script:
  - |
    if [[ "$TRAVIS_RUST_VERSION" == nightly ]]; then
      cargo fmt --all -- --check
    fi
  - cargo build --verbose --all
  - cargo test --verbose --all
