[package]
name = "error-handling"
version = "0.1.0"
edition = "2021"

[dependencies]
lambda_runtime = { path = "../../lambda-runtime" }
serde = "1.0.217"
serde_json = "1.0.137"
simple-error = "0.3.1"
tokio = { version = "1", features = ["macros"] }
