name: Check Lambda Events

on:
  push:
    paths:
      - 'lambda-events/**'
  pull_request:
    paths:
      - 'lambda-events/**'

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          - "1.64.0" # Current MSRV
          - stable
    env:
      RUST_BACKTRACE: 1
    steps:
      - uses: actions/checkout@v3

      - name: Build events
        uses: ./.github/actions/rust-build
        with:
          package: aws_lambda_events
          toolchain: ${{ matrix.toolchain}}
  check-event-features:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: dtolnay/rust-toolchain@stable
      - uses: Swatinem/rust-cache@v2

      - name: Test individual event features
        run: make check-event-features
